const body=document.body;const sidebar=document.getElementById('sidebar');const toast=document.getElementById('toast');const dashboard=document.getElementById('dashboardPage');const simplePage=document.getElementById('simplePage');const simpleTitle=document.getElementById('simpleTitle');
function showToast(message){toast.textContent='✓  '+message;toast.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.hidden=true,2600)}
function openPage(page){if(page==='dashboard'){dashboard.hidden=false;simplePage.hidden=true}else{dashboard.hidden=true;simplePage.hidden=false;simpleTitle.textContent={production:'الإنتاج',stock:'المخزون',workers:'العمال',reports:'التقارير',settings:'الإعدادات'}[page]||'القسم'}document.querySelectorAll('.nav-item').forEach(button=>button.classList.toggle('active',button.dataset.page===page));if(window.innerWidth<701)sidebar.classList.remove('open')}
document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>openPage(button.dataset.page)));
document.querySelectorAll('[data-page-link]').forEach(button=>button.addEventListener('click',()=>openPage(button.dataset.pageLink)));
document.getElementById('menuButton').addEventListener('click',()=>sidebar.classList.toggle('open'));
document.getElementById('notifyButton').addEventListener('click',()=>showToast('لا توجد إشعارات جديدة'));
document.getElementById('scrollTask').addEventListener('click',()=>document.getElementById('taskSection').scrollIntoView({behavior:'smooth',block:'center'}));
document.getElementById('saveTask').addEventListener('click',()=>{const name=document.getElementById('taskName').value.trim();const message=document.getElementById('formMessage');if(!name){message.textContent='اكتب اسم المهمة أولاً';document.getElementById('taskName').focus();return}message.textContent='تم حفظ المهمة: '+name;document.getElementById('taskName').value='';showToast('تم حفظ المهمة بنجاح')});
document.getElementById('stockSearch').addEventListener('input',event=>{const term=event.target.value.trim().toLowerCase();document.querySelectorAll('.stock-item').forEach(row=>row.style.display=row.textContent.toLowerCase().includes(term)?'grid':'none')});
const savedTheme=localStorage.getItem('madar-simple-theme')||'dark';if(savedTheme==='light')body.classList.add('light');function updateThemeButton(){document.getElementById('themeButton').innerHTML=body.classList.contains('light')?'🌙 <span>النمط الليلي</span>':'☀️ <span>النمط الشمسي</span>'}updateThemeButton();document.getElementById('themeButton').addEventListener('click',()=>{body.classList.toggle('light');localStorage.setItem('madar-simple-theme',body.classList.contains('light')?'light':'dark');updateThemeButton()});
